### ISSUE TITLE
Specify minimum node version

### ISSUE THREAD

**Issue by alexellis** [openfaas-incubator/skej#3]
alex@host:~/dev/scheduler/skej$ node index.js 
/home/alex/dev/scheduler/skej/skej/index.js:8
        const {invoke, compose} = FaaS('http://localhost:8080');
              ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/alex/dev/scheduler/skej/index.js:3:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by austinfrey** [comment]
Will do. I might just make changes to allow for more versions. thanks for the feedback

**Comment by austinfrey** [comment]
I updated to README to state minimum Node version for now. #5

**Comment by developius** [comment]
@austinfrey you can do this in `package.json` too, which is often helpful to the end user:

```json
{
  "name": "skej",
  "engines" : { "node" : ">=6.4.0" }
}
```

**Comment by austinfrey** [comment]
@developius thanks for the tip!
